# Runner
FROM php:8.2

WORKDIR /app

COPY . ./

RUN apt update && \
    apt install -y ca-certificates cron curl tar unzip libpng-dev libxml2-dev libzip-dev libmagickwand-dev && \
    apt clean && \
    docker-php-ext-configure zip && \
    docker-php-ext-install bcmath gd pdo_mysql zip && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    composer install --optimize-autoloader --no-dev

RUN echo "* * * * * /usr/local/bin/php /var/www/html/artisan schedule:run >> /dev/null 2>&1" >> /var/spool/cron/crontabs/root

RUN pecl install imagick && \
    docker-php-ext-enable imagick;

RUN chmod +x docker/prod/docker_entrypoint_queue.sh
