# Build Front-End
FROM node:18-alpine as node-build

WORKDIR /app

COPY . ./

RUN npm install --quiet && \
    rm -r public/build/* && \
    npm run build-dev && \
    rm -r node_modules

# Runner
FROM php:8.2

WORKDIR /app

COPY . ./
COPY --from=node-build /app/public/build public/build

RUN apt update && \
    apt upgrade -y && \
    apt install -y ca-certificates cron curl tar unzip libpng-dev libxml2-dev libzip-dev && \
    apt clean && \
    docker-php-ext-configure zip && \
    docker-php-ext-install bcmath gd pdo_mysql zip && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer install --optimize-autoloader --no-dev && \
    php artisan cache:clear && \
    php artisan route:clear && \
    php artisan config:cache && \
    php artisan view:cache

RUN chmod +x docker/prod/docker_entrypoint_web.sh

EXPOSE 8000
