version: "3.3"

services:
  equipamentos:
    container_name: equipamentos
    build: .
    volumes:
      - /var/www/equipamentos:/var/www/html
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - database
      - socketi
    restart: always
    entrypoint: './docker_entrypoint_web.sh'
  equipamentos_queue:
    container_name: equipamentos_queue
    build: .
    volumes:
      - /var/www/equipamentos:/var/www/html
    networks:
      - database
      - socketi
    restart: always
    entrypoint: './docker_entrypoint_queue.sh'


networks:
  database:
    name: database
  socketi:
    name: socketi
