version: "3.3"

services:
    equipamentos:
        image: equipamentos
        container_name: equipamentos
        build:
            context: projeto
            dockerfile: docker/prod/Dockerfile-web
            args:
                - NEW_RELIC_AGENT_VERSION=10.2.0.314
                - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
                - NEW_RELIC_APP_NAME=equipamentos
        volumes:
            - /var/www/equipamentos/storage:/app/storage
        ports:
            - 8000:8000
        expose:
            - 8000
        networks:
            - database
            - socketi
            - nginx
            - newrelic
        restart: always
        entrypoint: 'docker/prod/docker_entrypoint_web.sh'
    equipamentos_queue:
        image: equipamentos
        container_name: equipamentos_queue
        build:
            context: projeto
            dockerfile: docker/prod/Dockerfile-queue
        volumes:
            - /var/www/equipamentos/storage:/app/storage
        networks:
            - database
            - socketi
            - nginx
        restart: always
        entrypoint: 'docker/prod/docker_entrypoint_queue.sh'
    socketi:
        container_name: socketi
        image: quay.io/soketi/soketi:1.4-16-debian
        ports:
            - 6001:6001
            - 9601:9601
        expose:
            - 6001
            - 9601
        restart: always
        networks:
            - socketi
            - nginx
        environment:
            DEBUG: false
            SOKETI_METRICS_ENABLED: true
            SOKETI_DEBUG: 0
    newrelic-php-daemon:
        container-name: newrelic-php-daemon
        image: newrelic/php-daemon
        networks:
            - newrelic

networks:
    database:
        name: database
    socketi:
        name: socketi
    nginx:
        name: nginx
    newrelic:
        name: newrelic
