# Runner
FROM php:8.2

WORKDIR /app

COPY . ./

RUN apt update && \
    apt install -y ca-certificates cron curl tar unzip libpng-dev libxml2-dev libzip-dev wget && \
    apt clean && \
    docker-php-ext-configure zip && \
    docker-php-ext-install bcmath gd pdo_mysql zip && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    echo "* * * * * /usr/local/bin/php /var/www/html/artisan schedule:run >> /dev/null 2>&1" >> /var/spool/cron/crontabs/root && \
    composer install --optimize-autoloader --no-dev

RUN wget https://github.com/elastic/apm-agent-php/releases/download/v1.8.3/apm-agent-php_1.8.3_all.deb && \
    dpkg -i apm-agent-php_1.8.3_all.deb && \
    rm apm-agent-php_1.8.3_all.deb

RUN chmod +x docker/prod/docker_entrypoint_queue.sh
