# Build Front-End
FROM node:18-alpine as node-build

WORKDIR /app

COPY . ./

RUN npm install  && \
    npm run build

# Runner
FROM php:8.2-fpm

WORKDIR /app

RUN apt update && \
    apt install -y ca-certificates cron curl tar unzip libpng-dev libxml2-dev libzip-dev wget && \
    apt clean && \
    docker-php-ext-configure  zip && \
    docker-php-ext-install bcmath gd pdo_mysql zip opcache xml && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . ./
COPY --from=node-build /app/public/build public/build

RUN composer install --optimize-autoloader --no-dev
RUN chmod +x docker/prod/docker_entrypoint_web.sh
RUN chmod -R 755 public/build
RUN cp /app/docker/prod/config-web.ini /usr/local/etc/php/conf.d/config.ini
