version: "3.3"

services:
    equipamentos:
        image: equipamentos
        container_name: equipamentos
        build:
            context: projeto
            dockerfile: docker/prod/Dockerfile-web
        volumes:
            - /var/www/equipamentos/storage:/app/storage
            - equipamentos-public:/app/public
            - /var/www/equipamentos/elastic-apm-web.ini:/usr/local/etc/php/conf.d/elastic-apm-web.ini:ro
        ports:
            - 9000:9000
        expose:
            - 9000
        networks:
            - database
            - nginx
            - elastic
        links:
            - redis
            - socketi
        restart: always
        entrypoint: 'docker/prod/docker_entrypoint_web.sh'
    equipamentos_queue:
        image: equipamentos
        container_name: equipamentos_queue
        build:
            context: projeto
            dockerfile: docker/prod/Dockerfile-queue
        volumes:
            - /var/www/equipamentos/storage:/app/storage
            - /var/www/equipamentos/elastic-apm-queue.ini:/usr/local/etc/php/conf.d/elastic-apm-queue.ini:ro
        networks:
            - database
            - nginx
            - elastic
        links:
            - redis
            - socketi
        restart: always
        entrypoint: 'docker/prod/docker_entrypoint_queue.sh'
    socketi:
        container_name: socketi
        image: quay.io/soketi/soketi:1.4-16-debian
        ports:
            - 6001:6001
            - 9601:9601
        expose:
            - 6001
            - 9601
        restart: always
        networks:
            - nginx
        environment:
            DEBUG: false
            SOKETI_METRICS_ENABLED: true
            SOKETI_DEBUG: 0
    autoheal:
        restart: always
        image: willfarrell/autoheal
        environment:
            - AUTOHEAL_CONTAINER_LABEL=all
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    redis:
        container_name: redis
        image: redis
        ports:
            - 6379:6379
        expose:
            - 6379
        restart: always
        deploy:
            resources:
                limits:
                    memory: 200M

networks:
    database:
        name: database
        external: true
    nginx:
        name: nginx
        external: true
    elastic:
        name: elastic
        external: true

volumes:
    equipamentos-public:
        name: equipamentos-public
