# Runner
FROM php:8.2

WORKDIR /app

RUN apt update && \
    apt install -y ca-certificates cron curl tar unzip libpng-dev libxml2-dev libzip-dev wget && \
    apt clean && \
    docker-php-ext-configure zip && \
    docker-php-ext-install bcmath gd pdo_mysql zip && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    echo "* * * * * /usr/local/bin/php /var/www/html/artisan schedule:run >> /dev/null 2>&1" >> /var/spool/cron/crontabs/root

COPY . ./
RUN composer install --optimize-autoloader --no-dev
RUN chmod +x docker/prod/docker_entrypoint_queue.sh
