version: "3.3"

services:
    equipamentos:
        image: equipamentos
        container_name: equipamentos
        build:
            context: projeto
            dockerfile: docker/prod/Dockerfile-web
        volumes:
            - /var/www/equipamentos/storage/web:/app/storage
        ports:
            - 8000:8000
        expose:
            - 8000
        networks:
            - database
            - socketi
            - nginx
        restart: always
        entrypoint: 'docker/prod/docker_entrypoint_web.sh'
    equipamentos_queue:
        image: equipamentos
        container_name: equipamentos_queue
        build:
            context: projeto
            dockerfile: docker/prod/Dockerfile-queue
        volumes:
            - /var/www/equipamentos/storage/queue:/app/storage
        networks:
            - database
            - socketi
            - nginx
        restart: always
        entrypoint: 'docker/prod/docker_entrypoint_queue.sh'
    socketi:
        container_name: socketi
        image: quay.io/soketi/soketi:1.4-16-debian
        ports:
            - 6001
            - 9601
        expose:
            - 6001
            - 9601
        restart: always
        networks:
            - socketi
            - nginx

networks:
    database:
        name: database
    socketi:
        name: socketi
    nginx:
        name: nginx
