name: 'Build Assets'

on:
  pull_request:
    paths:
      - 'resources/css/**'
      - 'resources/js/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - run: git checkout ${{ steps.extract_branch.outputs.branch }}

      - run: rm -r public/build/*

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'
          check-latest: true
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm install

      - name: Compile assets for production
        run: npm run build

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Github Action - Build Assets
          file_pattern: public/build/
          push_options: --force
