name: 'Checks, Builds, Tests'

on:
  pull_request:
    paths:
      - '**.php'
      - 'resources/**'

jobs:
  checks:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=5s --health-retries=6

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          check-latest: true
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm install

      - name: Run Eslint
        run: npm run eslint

      - name: Run Build
        run: npm run build

      - name: Install composer dependencies
        run: |
          composer install --no-scripts --optimize-autoloader

      - name: Run PHP Code Sniffer
        run: |
          ./vendor/bin/phpcs

      - name: CP .env
        run: |
          cp .env.ci .env

      - name: Generate Key
        run: |
            php artisan key:generate

      - name: Install Ubuntu Dependencies
        run: |
          apt install -y libmagickwand-dev

      - name: Setup PHP with http from source
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: imagick

      - name: Run Testsuite
        run: php artisan test

      - name: Check composer vulnerabilities
        run: composer audit --locked

      - name: Check npm vulnerabilities
        run: npm audit
