name: 'ESLint'

on:
  pull_request:
    paths:
      - 'resources/**'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          check-latest: true
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm install

      - name: Run Eslint
        run: npm run eslint
