name: 'PHP CS && Test'

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Install PHP_CodeSniffer
      run: |
        curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        php phpcs.phar --version

    - uses: thenabeel/action-phpcs@v8
      with:
        phpcs_path: php phpcs.phar
        standard: phpcs.xml

  laravel-test:
    needs: phpcs
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: CP .env
      run: |
        cp .env.ci .env

    - name: Generate Key
      run: |
          php artisan key:generate

    - name: Run Testsuite
      run: php artisan test
